### ISSUE TITLE
Add a section about friendly/similar repositories?

### ISSUE THREAD

**Issue by stanislaw** [EvgenyKarkan/EKAlgorithms#92]
Hello, @EvgenyKarkan.

How about adding section with similar repositories? I think [this growing one](https://github.com/sagivo/algorithms) is a good candiate to start section.

I haven't been doing anything on this algorithms topic during these latest months because of almost entire focus on patterns/architecture area so no contributions :smile:  Anyway I like it a lot that we created and now have this basic base of algorithms just in case if a need in some of them raises! Good work!

Thanks,

Stanislaw

**Comment by stanislaw** [comment]
Also note how they nicely arrange problems and solutions into the tables. I think EKAlgorithms repository could make friends with [sagivo/algorithms](https://github.com/sagivo/algorithms) and vice versa.

**Comment by EvgenyKarkan** [comment]
Hi @stanislaw, I don't mind. 
Moreover, it will be cool if maintainer add our work as friendly/similar repo too :)

**Comment by stanislaw** [comment]
Looks like @sagivo is hesitating to add us back as friends for some reason. Anyway for us it is still good to have link to friendly repository because in Open Source networking is everything. @EvgenyKarkan, I think you'll agree with that. So I am closing this.

**Comment by EvgenyKarkan** [comment]
Hi @stanislaw !
Well, I am not sad about it, & hope you too :)
It's up to maintainer.

**Comment by stanislaw** [comment]
Yes and yes :smile:
